apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan01
  namespace: coll-gestlck-be--datagrid-83-test-by-martinelli
spec:
  container:
    memory: 2Gi
  replicas: 5
  service:
    type: Cache
    replicationFactor: 2
    container:
      storageClassName: rhosp-cinder
      storage: 2Gi 
      ephemeralStorage: false

