apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan01
  namespace: myPROJ
spec:
  container:
    memory: 2Gi
  replicas: 5
  service:
    type: Cache
    replicationFactor: 3
    container:
      storageClassName: rhosp-cinder
      storage: 2Gi 
      ephemeralStorage: false

