apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: infinispan01
  namespace: coll-gestlck-be--datagrid-83-test-by-martinelli
spec:
  cluster: infinispan01
  config: |
    create cache --template=org.infinispan.DIST_SYNC mycache
    put --cache=mycache hello world
    put --cache=mycache hola mundo
