apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infinispan-backup-manager
  namespace: myPROJ
subjects:
- kind: ServiceAccount
  name: infinispan-backup-manager
  namespace: myPROJ
roleRef:
  kind: Role
  name: infinispan-backup-manager
  apiGroup: rbac.authorization.k8s.io

