apiVersion: infinispan.org/v2alpha1
kind: Backup
metadata:
  name: backup--infinispan01--2024-08-29
  namespace: myPROJ
spec:
  cluster: infinispan01
  volume:
    storage: 1Gi
    storageClassName: rhosp-cinder
