apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infinispan-backup-manager
  namespace: myPROJ
rules:
- apiGroups: ["infinispan.org"]
  resources: ["backups"]
  verbs: ["create","list","delete","update","get","patch","watch"]
