apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: my-declarative-distributed-persistent-x-protostream-cache-03
  namespace: myPROJ
spec:
  clusterName: infinispan01
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "3"
      segments: "256"
      capacityFactor: "0.9"
      statistics: "true"
      encoding:
        mediaType: "application/x-protostream"
      persistence:
        passivation: "false"
        fileStore:
          shared: "false"
          data:
            path: "/opt/infinispan/server/data"
